apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: uidexample
resources:
- rolebinding.yaml
- deployment.yaml
- serviceaccount.yaml
- buildconfig.yaml
- imagestream.yaml

configurations:
  - nameReference.yaml
